\c db_business

-- Seed data for employees table
INSERT INTO employees (employee_username, employee_email)
VALUES
  ('john_doe', 'john.doe@example.com'),
  ('jane_smith', 'jane.smith@example.com'),
  ('alexander_wang', 'alexander.wang@example.com'),
  ('emily_jones', 'emily.jones@example.com'),
  ('michael_brown', 'michael.brown@example.com'),
  ('olivia_smith', 'olivia.smith@example.com'),
  ('benjamin_wilson', 'benjamin.wilson@example.com'),
  ('sophia_johnson', 'sophia.johnson@example.com'),
  ('daniel_anderson', 'daniel.anderson@example.com'),
  ('isabella_davis', 'isabella.davis@example.com'),
  ('william_taylor', 'william.taylor@example.com'),
  ('ava_thomas', 'ava.thomas@example.com'),
  ('james_lee', 'james.lee@example.com'),
  ('mia_clark', 'mia.clark@example.com'),
  ('benjamin_rodriguez', 'benjamin.rodriguez@example.com'),
  ('charlotte_hall', 'charlotte.hall@example.com'),
  ('david_martinez', 'david.martinez@example.com'),
  ('harper_jackson', 'harper.jackson@example.com'),
  ('logan_miller', 'logan.miller@example.com'),
  ('madison_white', 'madison.white@example.com'),
  ('ethan_taylor', 'ethan.taylor@example.com'),
  ('ava_moore', 'ava.moore@example.com'),
  ('noah_anderson', 'noah.anderson@example.com'),
  ('emma_thompson', 'emma.thompson@example.com'),
  ('oliver_davis', 'oliver.davis@example.com'),
  ('sophia_martin', 'sophia.martin@example.com');

-- Seed data for employee_names table
INSERT INTO employee_names (employee_id, employee_first_name, employee_last_name)
VALUES
  (1, 'John', 'Doe'),
  (2, 'Jane', 'Smith'),
  (3, 'Alexander', 'Wang'),
  (4, 'Emily', 'Jones'),
  (5, 'Michael', 'Brown'),
  (6, 'Olivia', 'Smith'),
  (7, 'Benjamin', 'Wilson'),
  (8, 'Sophia', 'Johnson'),
  (9, 'Daniel', 'Anderson'),
  (10, 'Isabella', 'Davis'),
  (11, 'William', 'Taylor'),
  (12, 'Ava', 'Thomas'),
  (13, 'James', 'Lee'),
  (14, 'Mia', 'Clark'),
  (15, 'Benjamin', 'Rodriguez'),
  (16, 'Charlotte', 'Hall'),
  (17, 'David', 'Martinez'),
  (18, 'Harper', 'Jackson'),
  (19, 'Logan', 'Miller'),
  (20, 'Madison', 'White'),
  (21, 'Ethan', 'Taylor'),
  (22, 'Ava', 'Moore'),
  (23, 'Noah', 'Anderson'),
  (24, 'Emma', 'Thompson'),
  (25, 'Oliver', 'Davis'),
  (26, 'Sophia', 'Martin');

-- Seed data for employee_departments table
-- INSERT INTO employee_departments (employee_id, department_id)
-- VALUES
--   (1, 1), -- Assuming department_id = 1 exists
--   (2, 2),
--   (3, 1),
--   (4, 3),
--   (5, 2),
--   (6, 1),
--   (7, 4),
--   (8, 3),
--   (9, 2),
--   (10, 4),
--   (11, 1),
--   (12, 3),
--   (13, 2),
--   (14, 1),
--   (15, 4),
--   (16, 2),
--   (17, 3),
--   (18, 1),
--   (19, 4),
--   (20, 2),
--   (21, 3),
--   (22, 1),
--   (23, 4),
--   (24, 2),
--   (25, 3);

-- Seed data for employee_salaries table
INSERT INTO employee_salaries (employee_id, employee_salary_pounds)
VALUES
  (1, 50000),
  (2, 60000),
  (3, 55000),
  (4, 52000),
  (5, 58000),
  (6, 51000),
  (7, 59000),
  (8, 54000),
  (9, 57000),
  (10, 53000),
  (11, 62000),
  (12, 56000),
  (13, 57000),
  (14, 51000),
  (15, 59000),
  (16, 56000),
  (17, 54000),
  (18, 52000),
  (19, 61000),
  (20, 55000),
  (21, 54000),
  (22, 52000),
  (23, 61000),
  (24, 53000),
  (25, 55000);